# Generated by Django 5.2.1 on 2025-07-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_register_time', models.DateTimeField()),
                ('end_register_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming '), ('ongoing', 'Ongoing '), ('completed', 'Completed'), ('waiting', 'Waiting')], default='upcoming', max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
