# Generated by Django 5.2.1 on 2025-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming '), ('ongoing', 'Ongoing '), ('completed', 'Completed')], default='upcoming', max_length=10),
        ),
    ]
