# Generated by Django 5.2.1 on 2025-05-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming '), ('ongoing', 'Ongoing '), ('completed', 'Completed'), ('waiting', 'Waiting')], default='upcoming', max_length=10),
        ),
    ]
